### ISSUE TITLE
How to set image as the background of toolbar

### ISSUE THREAD

**Issue by fzdm** [maphongba008/react-native-animated-header#1]
Hi,
I tried toolbarColor to set transparent.
But the bg image is empty, unable to achieve the desired effect.

**Comment by maphongba008** [comment]
Hi there, I don't get your mid
Could you show me your expected image?

**Comment by fzdm** [comment]
I wish I could be like this：<img width="305" alt="header" src="https://user-images.githubusercontent.com/40664430/44309346-f526a400-a3f7-11e8-9465-fdf2094416f1.png">

And can I define the toolbar height?

**Comment by maphongba008** [comment]
So, do you want the image doesn't disappear, only resize?
In the current version, it's not allow to define the toolbar height, but you can fork and edit the `initToolbarHeight`  in `Header.js` file

**Comment by fzdm** [comment]
Thank you. I solved this problem by modifying the file.
